### ISSUE TITLE
[Suggestion]: using book and quill

### ISSUE THREAD

**Issue by k1r0s** [Mrbysco/Spelled#5]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Why not just use book and quill? spell book is messy

**Comment by Mrbysco** [comment]
The spell book was made to make it easier to create spells, a book and quill would still force people to write out and and will only annoy people if they sign the book and it won't work because they typo'd
