### ISSUE TITLE
[Bug]: Fractionis not breaking some blocks.

### ISSUE THREAD

**Issue by PyroBurnem** [Mrbysco/Spelled#8]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.2.1

### Minecraft version

1.18.2

### Mod version

1.18.2-0.2.3

### Java version

1.8.0_51 (i think this is it, im using the bundled version with the mc launcher)

### Issue Description

Fractionis is not able to break any material with a mining level of 1 or higher. It is able to break dirt and wood with ease, but is unable to break stone, cobblestone, etc. This includes when I am at max level.

Speaking of wood, it is only able to break logs. Wooden products such as doors, planks and stairs cannot be broken using fractionis.

While I have selected "running a modpack", this issue is reproducible in a fresh install with only the mod (and Patchouli).

**Comment by PyroBurnem** [comment]
Disingenuous to say that fractionis is not breaking blocks, as it implies that fractionis does not break any block, which is not the case. Title amended.

**Comment by Mrbysco** [comment]
I've added new words in 1.19.2 which can increase the power of fractionis
