### ISSUE TITLE
[Suggestion]: Ability to move player camera while chat is open

### ISSUE THREAD

**Issue by UltrascatterRED** [Mrbysco/Spelled#9]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Whenever typing an incantation, especially in combat, I find it really difficult to actually hit my target because the player camera is locked in place while chat is open. Therefore, I think it would be a great QoL change to implement allowing the player to look around while typing in chat to make spellcasting a bit smoother. 
To clarify, I am not suggesting player _movement_ with chat open, since that would obviously create conflicting inputs.

**Comment by Mrbysco** [comment]
Have you crafted a Spell book yet? it allows you to set a spell onto the book and right-click it to fire that spell
